env:
  BUILD_IS_RELEASE: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release/**'
    }}
  BUILD_JAVA_DIST: temurin
  BUILD_JAVA_VERSION: '17'
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IDE_SIGNING_ALIAS: ${{ secrets.IDE_SIGNING_ALIAS }}
  IDE_SIGNING_AUTH_PASS: ${{ secrets.IDE_SIGNING_AUTH_PASS }}
  IDE_SIGNING_AUTH_USER: ${{ secrets.IDE_SIGNING_AUTH_USER }}
  IDE_SIGNING_KEY_BIN: ${{ secrets.IDE_SIGNING_KEY_BIN }}
  IDE_SIGNING_KEY_PASS: ${{ secrets.IDE_SIGNING_KEY_PASS }}
  IDE_SIGNING_STORE_PASS: ${{ secrets.IDE_SIGNING_STORE_PASS }}
  IDE_SIGNING_URL: ${{ secrets.IDE_SIGNING_URL }}
  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MVN_PASSWORD }}
  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MVN_USERNAME }}
  ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.MVN_SIGNING_KEY }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.MVN_SIGNING_KEY_ID }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.MVN_SIGNING_KEY_PASSWORD
    }}
  ReleaseAndroidIDE: ${{ github.ref == 'refs/heads/main' }}
jobs:
  build_apk:
    name: Build APK
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Cancel previous runs
      uses: styfle/cancel-workflow-action@0.12.1
      with:
        access_token: ${{ github.token }}
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: ${{ env.BUILD_JAVA_DIST }}
        java-version: ${{ env.BUILD_JAVA_VERSION }}
    - continue-on-error: true
      name: Change Gradle wrapper permissions
      run: chmod +x ./gradlew
    - continue-on-error: true
      name: Restore cache
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          '
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      name: Assemble ${{ matrix.build_type }} APK
      run: 'build_type=${{ matrix.build_type }}

        ./gradlew :app:assemble${build_type^}

        '
    - continue-on-error: true
      name: Copy ${{ matrix.build_type }} APK
      run: 'cp app/build/outputs/apk/${{ matrix.build_type }}/app-*.apk ./

        '
    - continue-on-error: true
      name: Upload arm64-v8a ${{ matrix.build_type }} APK
      uses: actions/upload-artifact@v4
      with:
        name: apk-arm64-v8a-${{ matrix.build_type }}
        path: app-arm64-v8a-${{ matrix.build_type }}.apk
    - continue-on-error: true
      name: Upload armeabi-v7a ${{ matrix.build_type }} APK
      uses: actions/upload-artifact@v4
      with:
        name: apk-armeabi-v7a-${{ matrix.build_type }}
        path: app-armeabi-v7a-${{ matrix.build_type }}.apk
    - continue-on-error: true
      name: Upload x86_64 ${{ matrix.build_type }} APK
      uses: actions/upload-artifact@v4
      with:
        name: apk-x86_64-${{ matrix.build_type }}
        path: app-x86_64-${{ matrix.build_type }}.apk
    - continue-on-error: true
      if: ${{ matrix.build_type == 'release' }}
      name: Upload ${{ matrix.build_type }} mappings
      uses: actions/upload-artifact@v4
      with:
        name: release-mappings
        path: '**/build/outputs/mapping'
    strategy:
      matrix:
        build_type:
        - debug
        - release
  publish:
    if: 'always()

      && github.ref == ''refs/heads/main''

      && github.event_name != ''pull_request''

      && needs.build_apk.result == ''success''

      && needs.run_unit_tests.result == ''success''

      && needs.run_tooling_api_tests.result == ''success''

      '
    name: Publish release
    needs:
    - build_apk
    - run_unit_tests
    - run_tooling_api_tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: ${{ env.BUILD_JAVA_DIST }}
        java-version: ${{ env.BUILD_JAVA_VERSION }}
    - continue-on-error: true
      name: Download arm64-v8a APK
      uses: actions/download-artifact@v4
      with:
        name: apk-arm64-v8a-release
    - continue-on-error: true
      name: Download x86_64 APK
      uses: actions/download-artifact@v4
      with:
        name: apk-x86_64-release
    - continue-on-error: true
      name: Download armeabi-v7a APK
      uses: actions/download-artifact@v4
      with:
        name: apk-armeabi-v7a-release
    - continue-on-error: true
      name: Change Gradle wrapper permissions
      run: chmod +x ./gradlew
    - continue-on-error: true
      name: Restore cache
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          '
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      name: Generate checksums
      run: 'mkdir -p build


        md5sum *.apk > build/CHECKSUMS-md5.txt

        sha256sum *.apk > build/CHECKSUMS-sha256.txt

        sha512sum *.apk > build/CHECKSUMS-sha512.txt


        find build -type f -name "CHECKSUMS*.txt" -exec echo {} \; -exec cat {} \;
        -exec echo "" \;

        '
    - continue-on-error: true
      name: Publish release
      run: ./gradlew nyxMake nyxMark nyxPublish publish release --stacktrace
    - continue-on-error: true
      if: ${{ always() }}
      name: Archive Nyx state file
      uses: actions/upload-artifact@v4
      with:
        name: .nyx-state-${{ github.job }}.json
        path: build/nyx-state.json
  publish_snapshots:
    if: ${{ always() && github.ref != 'refs/heads/main' && github.event_name != 'pull_request'
      && needs.build_apk.result == 'success' }}
    name: Publish package snapshots
    needs:
    - build_apk
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: ${{ env.BUILD_JAVA_DIST }}
        java-version: ${{ env.BUILD_JAVA_VERSION }}
    - continue-on-error: true
      name: Change Gradle wrapper permissions
      run: chmod +x ./gradlew
    - continue-on-error: true
      name: Restore cache
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          '
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      name: Publish snapshots
      run: ./gradlew publishAllPublicationsToMavenCentralRepository --stacktrace
  run_connected_checks:
    if: false
    name: Run connected checks
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Cancel previous runs
      uses: styfle/cancel-workflow-action@0.12.1
      with:
        access_token: ${{ github.token }}
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: ${{ env.BUILD_JAVA_DIST }}
        java-version: ${{ env.BUILD_JAVA_VERSION }}
    - continue-on-error: true
      name: Change Gradle wrapper permissions
      run: chmod +x ./gradlew
    - continue-on-error: true
      name: Restore cache
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          '
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      name: Run connected checks
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        arch: x86_64
        profile: Nexus 6
        script: ./gradlew connectedCheck
        target: ${{ matrix.target }}
    - continue-on-error: true
      if: ${{ always() }}
      name: Upload test reports
      uses: actions/upload-artifact@v4
      with:
        name: test-results-android-tests-${{ matrix.api-level }}-${{ matrix.target
          }}
        path: '**/build/reports/androidTests/'
    strategy:
      matrix:
        api-level:
        - 26
        - 32
        target:
        - default
  run_tooling_api_tests:
    name: Build and test Tooling API
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: ${{ env.BUILD_JAVA_DIST }}
        java-version: ${{ env.BUILD_JAVA_VERSION }}
    - continue-on-error: true
      name: Change Gradle wrapper permissions
      run: chmod +x ./gradlew
    - continue-on-error: true
      name: Restore cache
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          '
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      env:
        ANDROIDIDE_TEST: true
        TEST_TOOLING_API_IMPL: true
      name: Run tooling API tests
      run: ./gradlew :subprojects:tooling-api-impl:build --continue
    - continue-on-error: true
      if: ${{ always() }}
      name: Upload test reports
      uses: actions/upload-artifact@v4
      with:
        name: test-results-tooling-api-tests
        path: '**/build/reports/tests/'
  run_unit_tests:
    name: Run unit tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: ${{ env.BUILD_JAVA_DIST }}
        java-version: ${{ env.BUILD_JAVA_VERSION }}
    - continue-on-error: true
      name: Change Gradle wrapper permissions
      run: chmod +x ./gradlew
    - continue-on-error: true
      name: Restore cache
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          '
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      env:
        ANDROIDIDE_TEST: true
      name: Run unit tests
      run: ./gradlew runTestsInCI --continue
    - continue-on-error: true
      if: ${{ always() }}
      name: Upload test reports
      uses: actions/upload-artifact@v4
      with:
        name: test-results-unit-tests
        path: '**/build/reports/tests/'
name: Build and test
on:
  repository_dispatch:
    types: trigger-ga___build.yml
